name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: git switch page
        run: git merge --theirs main
      - run: npm i
        run: rm -rf docs
      - run: npx parcel build --public-url . --dist-dir docs src/index.html
      - run: git add docs
      - run: git commit -m "v$(cat package.json | jq -r .version), $(date)"
