name: Pull Request Test

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ toJSON(github) }}"
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
