name: Test

on:
  workflow_dispatch:

jobs:
  test-on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo Workflow Dispatched
